dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install:

  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install --only-binary=numpy,scipy numpy nose scipy pytest sklearn;
      pip install tensorflow;
      pip install git+https://github.com/hycis/TensorGraph.git@master;
    fi

  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      pip3 install --only-binary=numpy,scipy numpy nose scipy pytest sklearn;
      pip3 install tensorflow;
      pip3 install git+https://github.com/hycis/TensorGraph.git@master;
    fi

script:
  - echo "TensorGraph Testing.."
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      python -m pytest test;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      python3 -m pytest test;
    fi
